<?php
    $arrEmotion = array();
    
    $arrEmotion= array(
        a => "おもろ",
        f => "かっこいい",
        j => "かわいい",
        l => "セクシー",
        b => "すごい",
        e => "なるほど～",
        c => "ほっこり",
        g => "泣ける",
        d => "あほ",
        h => "きもい",
        n => "しょうもない",
        m => "ひどい",
        k => "怖い",
        i => "悲しい",
    );

    $arrEmoWidth = array();
    
    $arrEmoWidth= array(
        a => 45,
        b => 45,
        c => 60,
        d => 30,
        e => 75,
        f => 75,
        g => 45,
        h => 45,
        i => 45,
        j => 60,
        k => 30,
        l => 60,
        m => 45,
        n => 90
    );

?>
