<?php
    $arrEmotion = array();

    $arrEmotion= array(
        a => "笑える",
        f => "かっこいい",
        j => "かわいい",
        b => "すごい",
        e => "なるほど～",
        c => "ほっこり",
        g => "泣ける",
        d => "あほ",
        l => "恥ずかしい",
        h => "きもい",
        n => "しょうもない",
        m => "ひどい",
        k => "怖い",
        i => "悲しい",
    );

    $arrEmoWidth = array();

    $arrEmoWidth= array(
        a => 45,
        b => 45,
        c => 60,
        d => 30,
        e => 75,
        f => 75,
        g => 45,
        h => 45,
        i => 45,
        j => 60,
        k => 30,
        l => 75,
        m => 45,
        n => 90
    );

    $arrAone = array();

    $arrAone = array(
        a,
        f,
        j,
        b,
        e,
        c,
        g,
        d,
        l,
        h,
        n,
        m,
        k,
        i,
    );
?>
